import { IPantryItems } from "../types";
export const pantryItems: IPantryItems = [
  {
    name: "Milk",
    quantity: 2,
    quantity_unit: "liters",
    date_added: new Date("2024-07-15T00:00:00Z"),
    expiration_date: new Date("2024-07-22T00:00:00Z"),
    category: "dairy",
    notes: "Low-fat",
    is_expired: false,
    image_url: "http://robohash.org/milk",
    location: "fridge",
  },
  {
    name: "Eggs",
    quantity: 12,
    quantity_unit: "pieces",
    date_added: new Date("2024-07-18T00:00:00Z"),
    expiration_date: new Date("2024-08-15T00:00:00Z"),
    category: "dairy",
    notes: "Free-range",
    is_expired: false,
    image_url: "http://robohash.org/eggs",
    location: "fridge",
  },
  {
    name: "Carrots",
    quantity: 1,
    quantity_unit: "kg",
    date_added: new Date("2024-07-10T00:00:00Z"),
    expiration_date: new Date("2024-07-30T00:00:00Z"),
    category: "vegetables",
    notes: "Organic",
    is_expired: false,
    image_url: "http://robohash.org/carrots",
    location: "fridge",
  },
  {
    name: "Chicken Breast",
    quantity: 4,
    quantity_unit: "pieces",
    date_added: new Date("2024-07-20T00:00:00Z"),
    expiration_date: new Date("2024-07-27T00:00:00Z"),
    category: "meat",
    notes: "Skinless, boneless",
    is_expired: false,
    image_url: "http://robohash.org/chicken_breasts",
    location: "fridge",
  },
  {
    name: "Ice Cream",
    quantity: 2,
    quantity_unit: "pints",
    date_added: new Date("2024-07-01T00:00:00Z"),
    expiration_date: new Date("2024-09-01T00:00:00Z"),
    category: "dessert",
    notes: "Vanilla",
    is_expired: false,
    image_url: "http://robohash.org/ice_cream",
    location: "freezer",
  },
  {
    name: "Peas",
    quantity: 1,
    quantity_unit: "bag",
    date_added: new Date("2024-06-15T00:00:00Z"),
    expiration_date: new Date("2024-12-15T00:00:00Z"),
    category: "vegetables",
    notes: "Frozen",
    is_expired: false,
    image_url: "http://robohash.org/peas",
    location: "freezer",
  },
  {
    name: "Fish Fillets",
    quantity: 5,
    quantity_unit: "pieces",
    date_added: new Date("2024-07-05T00:00:00Z"),
    expiration_date: new Date("2024-08-05T00:00:00Z"),
    category: "meat",
    notes: "Frozen cod",
    is_expired: false,
    image_url: "http://robohash.org/fish_fillets",
    location: "freezer",
  },
  {
    name: "Bread",
    quantity: 2,
    quantity_unit: "loaves",
    date_added: new Date("2024-07-14T00:00:00Z"),
    expiration_date: new Date("2024-07-21T00:00:00Z"),
    category: "bakery",
    notes: "Whole grain",
    is_expired: false,
    image_url: "http://robohash.org/bread",
    location: "shelf",
  },
  {
    name: "Peanut Butter",
    quantity: 1,
    quantity_unit: "jar",
    date_added: new Date("2024-06-20T00:00:00Z"),
    expiration_date: new Date("2025-06-20T00:00:00Z"),
    category: "spread",
    notes: "Crunchy",
    is_expired: false,
    image_url: "http://robohash.org/peanut_butter",
    location: "shelf",
  },
  {
    name: "Pasta",
    quantity: 3,
    quantity_unit: "packs",
    date_added: new Date("2024-07-12T00:00:00Z"),
    expiration_date: new Date("2025-01-12T00:00:00Z"),
    category: "grains",
    notes: "Spaghetti",
    is_expired: false,
    image_url: "http://robohash.org/pasta",
    location: "shelf",
  },
  {
    name: "Tomato Sauce",
    quantity: 4,
    quantity_unit: "cans",
    date_added: new Date("2024-06-30T00:00:00Z"),
    expiration_date: new Date("2025-06-30T00:00:00Z"),
    category: "canned",
    notes: "With basil",
    is_expired: false,
    image_url: "http://robohash.org/tomato_sauce",
    location: "shelf",
  },
  {
    name: "Frozen Pizza",
    quantity: 2,
    quantity_unit: "pieces",
    date_added: new Date("2024-07-15T00:00:00Z"),
    expiration_date: new Date("2024-09-15T00:00:00Z"),
    category: "prepared",
    notes: "Pepperoni",
    is_expired: false,
    image_url: "http://robohash.org/frozen_pizza",
    location: "freezer",
  },
  {
    name: "Lettuce",
    quantity: 1,
    quantity_unit: "head",
    date_added: new Date("2024-07-18T00:00:00Z"),
    expiration_date: new Date("2024-07-25T00:00:00Z"),
    category: "vegetables",
    notes: "Romaine",
    is_expired: false,
    image_url: "http://robohash.org/lettuce",
    location: "fridge",
  },
  {
    name: "Butter",
    quantity: 1,
    quantity_unit: "pack",
    date_added: new Date("2024-07-12T00:00:00Z"),
    expiration_date: new Date("2024-08-12T00:00:00Z"),
    category: "dairy",
    notes: "Unsalted",
    is_expired: false,
    image_url: "http://robohash.org/butter",
    location: "fridge",
  },
  {
    name: "Apples",
    quantity: 6,
    quantity_unit: "pieces",
    date_added: new Date("2024-07-15T00:00:00Z"),
    expiration_date: new Date("2024-08-01T00:00:00Z"),
    category: "fruits",
    notes: "Granny Smith",
    is_expired: false,
    image_url: "http://robohash.org/apples",
    location: "fridge",
  },
  {
    name: "Ground Beef",
    quantity: 2,
    quantity_unit: "packs",
    date_added: new Date("2024-07-20T00:00:00Z"),
    expiration_date: new Date("2024-07-25T00:00:00Z"),
    category: "meat",
    notes: "80% lean",
    is_expired: false,
    image_url: "http://robohash.org/ground_beef",
    location: "freezer",
  },
  {
    name: "Orange Juice",
    quantity: 1,
    quantity_unit: "bottle",
    date_added: new Date("2024-07-16T00:00:00Z"),
    expiration_date: new Date("2024-08-01T00:00:00Z"),
    category: "beverages",
    notes: "With pulp",
    is_expired: false,
    image_url: "http://robohash.org/orange_juice",
    location: "fridge",
  },
  {
    name: "Potatoes",
    quantity: 5,
    quantity_unit: "kg",
    date_added: new Date("2024-07-10T00:00:00Z"),
    expiration_date: new Date("2024-08-10T00:00:00Z"),
    category: "vegetables",
    notes: "Russet",
    is_expired: false,
    image_url: "http://robohash.org/potatoes",
    location: "shelf",
  },
];
